### ISSUE TITLE
Option to show more than 2 significant figures

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#18]
_From @arlake228 on March 14, 2015 12:47_

Original [issue 1040](https://code.google.com/p/perfsonar-ps/issues/detail?id=1040) created by arlake228 on 2015-01-08T11:00:04.000Z:

Hover over a throughput data point in graph and the figure shown is rouned to 2 signficant figures (e.g. 948Mbps from esmond is shown as &quot;950Mbps&quot;)

I would like to be able to configure it to show 3 significant figures.

_Copied from original issue: perfsonar/project#1038_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1040#c1) originally posted by arlake228 on 2015-01-09T10:01:24.000Z:

Related: owamp latency shows three decimal places but only two significant figures, e.g. "6.800ms". This is worse as the zeros imply an accuracy which isn't there.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1040#c2) originally posted by arlake228 on 2015-01-27T15:07:28.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1040#c3) originally posted by arlake228 on 2015-01-27T15:07:38.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Adding images from google code:
![screen shot 2015-01-08 at 10 13 33](https://cloud.githubusercontent.com/assets/634851/6810107/1896a9a0-d235-11e4-8486-506a37dcb979.png)
![screen shot 2015-01-09 at 09 59 57](https://cloud.githubusercontent.com/assets/634851/6810110/1ec18548-d235-11e4-9d9e-5f60d277af57.png)

**Comment by apertome** [comment]
This has mostly been addressed in the test results tables in 3.5. However, the graphs themselves have not been updated yet.

**Comment by apertome** [comment]
A more sane default (i.e. 3 significant figures) might be enough for the time being. The owamp latency bug above needs to be addressed as well.

**Comment by candlerb** [comment]
FYI this problem still exists in perfsonar 3.5, e.g. a throughput measurement of 929Mbps is displayed as 930Mbps.

I don't have any owamp latency graphs on this server, but ping latency shows as (e.g.) 0.300ms

**Comment by apertome** [comment]
I don't know that we will be making this configurable, but we should at least fix it so the default behavior isn't misleading.

**Comment by apertome** [comment]
Significant digits have been improved in the tooltips. We actually can't offer an option to show more digits for latency because the stats functions we're using giving us anything beyond tenths of milliseconds.

This commit also fixed #29
