### ISSUE TITLE
Report range buttons not displayed

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/graphs#44]
Using FF 49.0.1 under Win10 I don't see < > report range buttons like in attached screenshot.

![graph-range-buttons-not-visible](https://cloud.githubusercontent.com/assets/12281679/19470329/5655ec7a-951f-11e6-9c21-548deafe6bf0.png)

Under IE 11 the graphs are not visible at all :-(

**Comment by igarny** [comment]
I have the same view under: Chrome Version 54.0.2840.59 beta-m (64-bit)

**Comment by apertome** [comment]
Odd ... they seem to work for me. Will look into this further.

Does this happen on any host, or only ones that are on private networks?

**Comment by tonin** [comment]
Same for me on a host behind NAT.  You can see it at https://86.119.29.209/perfsonar-graphs/?source=10.0.182.240&dest=10.0.173.64&url=https%3A%2F%2F86.119.29.209%2Fesmond%2Fperfsonar%2Farchive%2F

**Comment by apertome** [comment]
Looks like a broken symlink, I just pushed a fix

**Comment by szymontrocha** [comment]
Should have it been in RC2? As for now it's not fixed, although changed a bit. See screens from FF and Chromium.
![report_rangeff](https://cloud.githubusercontent.com/assets/12281679/19973999/42efd298-a1e7-11e6-80ec-21c7ed444902.png)
![report_rangechromium](https://cloud.githubusercontent.com/assets/12281679/19974227/035492d0-a1e8-11e6-9250-83d5268bb481.png)

**Comment by apertome** [comment]
Yes, it was in RC2. I was hoping that what I did had fixed it, but that certainly doesn't look right. There are some major changes to the timerange selector coming in the final release, but those buttons will still be there. I'll make sure it gets fixed properly.

Are you on PC or Mac?

**Comment by szymontrocha** [comment]
PC

**Comment by apertome** [comment]
Interesting, we have Macs so that's what I do most of my testing on. I'll take another look from a PC as well. Thanks!

**Comment by szymontrocha** [comment]
To be precise the Chromium screen comes from another machine which is in fact based on Ubuntu.

**Comment by apertome** [comment]
I believe this is fixed, although I have not yet tested on a Windows box

**Comment by apertome** [comment]
Double-checked on Windows 10; verified it's fixed there, too.
