### ISSUE TITLE
Details graph is not loading under FF 51.0.1 and IE11 Win10

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/graphs#60]
With the latest changes the main page of toolkit works fine but when clicked on Details link to go to a separate page with graphs from regular tests it constantly show Loading page and doesn't load. I cleared cache, restarted FF even reinstalled it and it didn't help. Using FF 51.0.1 Win10. The same behaviour is observed with IE11.
I checked with other colleague PC using the same browser and the page also doesn't load. At the same time old release like http://psmall-poz1.man.poznan.pl/toolkit/ is loading properly.
![notloadingff](https://cloud.githubusercontent.com/assets/12281679/22587447/017042fe-ea02-11e6-9e83-1fe26c0412b7.png)

**Comment by szymontrocha** [comment]
Here is the url: http://150.254.160.17/toolkit/

**Comment by apertome** [comment]
That works for me, maybe there wasn't any data yet?

However, that is not the way it should behave when there is no data, so if that's the case there is still an issue.

**Comment by szymontrocha** [comment]
Yes, there was data as I was able to properly launched this window under Linux. Did you check it in a similar Win and FF environment?

**Comment by apertome** [comment]
I tried FF but I'm on a Mac. I can try Windows later today.

**Comment by apertome** [comment]
I was able to reproduce this in a Windows VM.

I believe I have a fix for this; I will push a new build later today and hopefully it will be fixed overnight by auto-updates. It turned out I was using a method for parsing URLs that's not compatible with Edge/IE. It should have worked in FF, and indeed when I look at this in FF (including on Windows), it does work. 

Thanks for catching this!

**Comment by szymontrocha** [comment]
I made some more testing (updated to latest packages today in my host) also using our development testing dashboard and launching graphs there. What I see is:

- under IE 11.xxx my host is not loading graphs, dashboard strangely displays "No data found for this timerange"

- under Edge 38.xxx both works OK

- under FF51.0.1 both don't work

All tested under Windows10. There must be something specific to browser support with this graphs plugin :-(

**Comment by apertome** [comment]
This should be fixed.  Can you verify?

**Comment by szymontrocha** [comment]
It still doesn't work for me :-( Under Edge my toolkit host works. I can't also see the graphs from development testing dashboard. I checked on other computers and it's the same. Do you have a test host which has public toolkit interface so that I can verify something else than just my host?

**Comment by apertome** [comment]
Ahh bad timing, looks like an issue I thought I had fixed isn't fixed yet, so it's not surprisng these won't load at the moment. Does it work if you change the time period to 1d instead of 1w?

**Comment by apertome** [comment]
I just pushed a fix for that other issue, so you can update again and try again.

You could also test on this host -- not a lot of data but enough to see if it's working:
http://ps-test.bldc.grnoc.iu.edu/toolkit/

**Comment by szymontrocha** [comment]
Is this in staging? There haven't been any updated packages since yesterday...

**Comment by apertome** [comment]
Hi Szymon, no, it's in nightly.

**Comment by szymontrocha** [comment]
Will it go to staging? I still don't see any updates

**Comment by apertome** [comment]
Hi Szymon, I just started a new build; it should be in the staging repo in  an hour or so, and then you should be able to update.

**Comment by szymontrocha** [comment]
Still nothing

[root@localhost psudouser]# date
Wed Feb 22 09:57:43 CET 2017
[root@localhost psudouser]# yum repolist
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * Internet2: mirror.in2p3.fr
 * base: ftp.wcss.pl
 * epel: ftp.upjs.sk
 * extras: ftp.wcss.pl
 * updates: ftp.wcss.pl
repo id                         repo name                                                                      status
Internet2                       Internet2 RPM Repository - software.internet2.edu - main                           10
Internet2-staging/x86_64        Internet2 Staging RPM Repository                                                1,190
Internet2-web100_kernel         Internet2 Web100 Kernel RPM Repository - software.internet2.edu - main            178
base/7/x86_64                   CentOS-7 - Base                                                                 9,363
epel/x86_64                     Extra Packages for Enterprise Linux 7 - x86_64                                 11,220
extras/7/x86_64                 CentOS-7 - Extras                                                                 263
updates/7/x86_64                CentOS-7 - Updates                                                                842
repolist: 23,066
[root@localhost psudouser]# yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * Internet2: mirror.in2p3.fr
 * base: ftp.wcss.pl
 * epel: ftp.upjs.sk
 * extras: ftp.wcss.pl
 * updates: ftp.wcss.pl
No packages marked for update
[root@localhost psudouser]#

**Comment by apertome** [comment]
Hi @szymontrocha, I figured out that I missed a step when I build the new package. It's rebuilding now and should be in the repo in about an hour. Sorry about that -- thanks for your patience.

**Comment by apertome** [comment]
I verified the package is in the staging repo.

**Comment by szymontrocha** [comment]
Here is after today's update:
- under IE 11.xxx works OK
- under Edge 38.xxx works OK
- under FF51.0.1 stopped working at all - a completely blank page opens from toolkit and an empty  graph box when using dashboard :-( (see attachment)
![graphs_dash_ff](https://cloud.githubusercontent.com/assets/12281679/23302737/57e10d5a-fa90-11e6-8c50-7c55830a9e00.png)

**Comment by apertome** [comment]
Spoke with Szymon this morning, he is still having issues that I cannot reproduce in Firefox. I will continue trying, but it also appears he is traveling until late this week, so this might need to wait.

**Comment by apertome** [comment]
I am confused by this, you mention issues with the Toolkit but your screenshot is maddash. Can you share the exact URL where you are having this problem? Thanks!

**Comment by szymontrocha** [comment]
That's because graphs launched from both sources are not loading! I guess these are the same libraries.
Launched from toolkit (and not loading): http://150.254.160.17/perfsonar-graphs/?source=150.254.160.17&dest=207.75.164.240&url=http%3A%2F%2F150.254.160.17%2Fesmond%2Fperfsonar%2Farchive%2F#start=1487948291&end=1488553091&summaryWindow=3600
From maddash - it's not loading any graphs I choose but of course my host is not in dev mash so it's not the same data

**Comment by apertome** [comment]
If you bring up the browser debugger, do you see errors in there?

Are you saying the page is *completely* blank?

**Comment by szymontrocha** [comment]
Yes, that's what I'm saying :-)
I checked on other PCs with Win10 and it's the same. There must be something specific to FF and Win10.
What should I look at debugger?
![empty_page](https://cloud.githubusercontent.com/assets/12281679/23556417/df2570e8-002c-11e7-86ab-93771de27dc3.png)

**Comment by szymontrocha** [comment]
Finally we catch something :)
![error](https://cloud.githubusercontent.com/assets/12281679/23614759/59e13fac-0284-11e7-896a-d5ce20fa5050.png)

**Comment by apertome** [comment]
@szymontrocha , I just pushed some changes to the staging repo that I hope will fix this. It turned out to be timezone-related, which explains why I couldn't reproduce the issue. If you could update your perfsonar-graphs package and see if that fixes it, that would be very helpful.

I also added some additional debug logging -- it would be helpful to see that text. You can find that by doing Inspect Element as before, going to Console, and searching within that window for "unknown timezone". The date string should be just to the right of that text.

If you could either take a screenshot of what it says on that line or copy and paste it, that would help me better understand what happened (the timezone is detected by parsing a string, but I have a feeling that whatever string comes up on your system is not what my code is expecting).

Thanks!

**Comment by szymontrocha** [comment]
Well done - seems it helped. See screenshot. I'm also attaching console output as you requested.
![graphs](https://cloud.githubusercontent.com/assets/12281679/23698233/1389f3d8-03eb-11e7-8ec4-0cab08113851.png)
![console](https://cloud.githubusercontent.com/assets/12281679/23698236/1812fbb6-03eb-11e7-877d-091998ce2eeb.png)

**Comment by apertome** [comment]
Great, thanks for your help!
