### ISSUE TITLE
graphData.cgi: hash iterator undefined behavior

### ISSUE THREAD

**Issue by vvidic** [perfsonar/graphs#86]
The following warning is reported for the loop after ``CONSOLIDATE BIDIRECTIONAL TESTS`` with perl 5.22.1 on Ubuntu 16.04/xenial:

```
Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x11e5010 at /usr/lib/perfsonar/graphs/cgi-bin/graphData.cgi line 867.
```

**Comment by apertome** [comment]
I believe I've fixed this, but I don't have a debian host to check it on.

Also of note, the method this is in was used by the old graphs and shouldn't really be called anywhere anymore, AFAIK. 

@vvidic can you verify the warning is fixed?

**Comment by vvidic** [comment]
It seems the error still appears when opening the ``/toolkit/`` page:

```
Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x1fa1010 at /usr/lib/perfsonar/graphs/cgi-bin/graphData.cgi line 871.
```

**Comment by tonin** [comment]
Same is still happening on an Ubuntu 14 host as of today:
```
Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x243a010 at /usr/lib/perfsonar/graphs/cgi-bin/graphData.cgi line 872.
```
Running perfsonar-toolkit-graphs version 4.0.0.2+20170704201108-1

**Comment by apertome** [comment]
Setup an Ubuntu VM so I could test this. Pretty sure it's fixed now, can you check it?

**Comment by tonin** [comment]
Last occurrence I saw was July 7th, cannot reproduce now.  It looks like we can close this.
